SELECT PEOPLE_TOTAL_2ND_DOSE/POPULATION RATIO_VACCINATED, *
FROM JHU_VACCINES A
JOIN (
    SELECT STATE, SUM(TOTAL_POPULATION) POPULATION
    FROM DEMOGRAPHICS
    GROUP BY 1
) B
ON A.STABBR=B.STATE
QUALIFY ROW_NUMBER() OVER(PARTITION BY PROVINCE_STATE ORDER BY DATE DESC)=1
ORDER BY DATE DESC, RATIO_VACCINATED DESC;
